namespace CarRentalApp.Forms
{
    partial class AvtomobiliForm
    {
        private System.ComponentModel.IContainer components = null;
        private CarRentalApp.Controls.BandedHeader header;
        private System.Windows.Forms.BindingSource bs;
        private System.Windows.Forms.BindingNavigator nav;
        private System.Windows.Forms.ToolStripButton navMoveFirst;
        private System.Windows.Forms.ToolStripButton navMovePrev;
        private System.Windows.Forms.ToolStripTextBox navPosition;
        private System.Windows.Forms.ToolStripLabel navCount;
        private System.Windows.Forms.ToolStripButton navMoveNext;
        private System.Windows.Forms.ToolStripButton navMoveLast;
        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.Label lblRegNomer;
        private System.Windows.Forms.TextBox txtRegNomer;
        private System.Windows.Forms.Label lblNomerKuzova;
        private System.Windows.Forms.TextBox txtNomerKuzova;
        private System.Windows.Forms.Label lblNomerDvigatelya;
        private System.Windows.Forms.TextBox txtNomerDvigatelya;
        private System.Windows.Forms.Label lblGodVypuska;
        private System.Windows.Forms.TextBox txtGodVypuska;
        private System.Windows.Forms.Label lblProbeg;
        private System.Windows.Forms.TextBox txtProbeg;
        private System.Windows.Forms.Label lblCenaAvto;
        private System.Windows.Forms.TextBox txtCenaAvto;
        private System.Windows.Forms.Label lblCenaDnyaProkata;
        private System.Windows.Forms.TextBox txtCenaDnyaProkata;
        private System.Windows.Forms.Label lblDataTO;
        private System.Windows.Forms.TextBox txtDataTO;
        private System.Windows.Forms.Label lblOtmetki;
        private System.Windows.Forms.TextBox txtOtmetki;
        private System.Windows.Forms.Label lblVozvrachen;
        private System.Windows.Forms.CheckBox chkVozvrachen;
        private System.Windows.Forms.Label lblKodMarki;
        private System.Windows.Forms.ComboBox cmbKodMarki;
        private System.Windows.Forms.Label lblKodMehanika;
        private System.Windows.Forms.ComboBox cmbKodMehanika;
        private CarRentalApp.Controls.ColoredButton btnFirst;
        private CarRentalApp.Controls.ColoredButton btnPrev;
        private CarRentalApp.Controls.ColoredButton btnNext;
        private CarRentalApp.Controls.ColoredButton btnLast;
        private CarRentalApp.Controls.ColoredButton btnAdd;
        private CarRentalApp.Controls.ColoredButton btnDel;
        private CarRentalApp.Controls.ColoredButton btnSave;
        private CarRentalApp.Controls.ColoredButton btnTable;
        private CarRentalApp.Controls.ColoredButton btnReport;
        private CarRentalApp.Controls.ColoredButton btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.header = new CarRentalApp.Controls.BandedHeader();
            this.bs = new System.Windows.Forms.BindingSource(this.components);
            this.nav = new System.Windows.Forms.BindingNavigator(this.components);
            this.navMoveFirst = new System.Windows.Forms.ToolStripButton();
            this.navMovePrev = new System.Windows.Forms.ToolStripButton();
            this.navPosition = new System.Windows.Forms.ToolStripTextBox();
            this.navCount = new System.Windows.Forms.ToolStripLabel();
            this.navMoveNext = new System.Windows.Forms.ToolStripButton();
            this.navMoveLast = new System.Windows.Forms.ToolStripButton();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.lblRegNomer = new System.Windows.Forms.Label();
            this.txtRegNomer = new System.Windows.Forms.TextBox();
            this.lblNomerKuzova = new System.Windows.Forms.Label();
            this.txtNomerKuzova = new System.Windows.Forms.TextBox();
            this.lblNomerDvigatelya = new System.Windows.Forms.Label();
            this.txtNomerDvigatelya = new System.Windows.Forms.TextBox();
            this.lblGodVypuska = new System.Windows.Forms.Label();
            this.txtGodVypuska = new System.Windows.Forms.TextBox();
            this.lblProbeg = new System.Windows.Forms.Label();
            this.txtProbeg = new System.Windows.Forms.TextBox();
            this.lblCenaAvto = new System.Windows.Forms.Label();
            this.txtCenaAvto = new System.Windows.Forms.TextBox();
            this.lblCenaDnyaProkata = new System.Windows.Forms.Label();
            this.txtCenaDnyaProkata = new System.Windows.Forms.TextBox();
            this.lblDataTO = new System.Windows.Forms.Label();
            this.txtDataTO = new System.Windows.Forms.TextBox();
            this.lblOtmetki = new System.Windows.Forms.Label();
            this.txtOtmetki = new System.Windows.Forms.TextBox();
            this.lblVozvrachen = new System.Windows.Forms.Label();
            this.chkVozvrachen = new System.Windows.Forms.CheckBox();
            this.lblKodMarki = new System.Windows.Forms.Label();
            this.cmbKodMarki = new System.Windows.Forms.ComboBox();
            this.lblKodMehanika = new System.Windows.Forms.Label();
            this.cmbKodMehanika = new System.Windows.Forms.ComboBox();
            this.btnFirst = new CarRentalApp.Controls.ColoredButton();
            this.btnPrev = new CarRentalApp.Controls.ColoredButton();
            this.btnNext = new CarRentalApp.Controls.ColoredButton();
            this.btnLast = new CarRentalApp.Controls.ColoredButton();
            this.btnAdd = new CarRentalApp.Controls.ColoredButton();
            this.btnDel = new CarRentalApp.Controls.ColoredButton();
            this.btnSave = new CarRentalApp.Controls.ColoredButton();
            this.btnTable = new CarRentalApp.Controls.ColoredButton();
            this.btnReport = new CarRentalApp.Controls.ColoredButton();
            this.btnClose = new CarRentalApp.Controls.ColoredButton();
            ((System.ComponentModel.ISupportInitialize)(this.bs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nav)).BeginInit();
            this.nav.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();

            // header
            this.header.Title = "АВТОМОБИЛИ";
            this.header.Size = new System.Drawing.Size(1100, 56);

            // nav
            this.nav.AddNewItem = null;
            this.nav.BindingSource = this.bs;
            this.nav.CountItem = this.navCount;
            this.nav.DeleteItem = null;
            this.nav.Dock = System.Windows.Forms.DockStyle.Top;
            this.nav.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                this.navMoveFirst, this.navMovePrev, this.navPosition, this.navCount,
                this.navMoveNext, this.navMoveLast });
            this.nav.MoveFirstItem = this.navMoveFirst;
            this.nav.MoveLastItem = this.navMoveLast;
            this.nav.MoveNextItem = this.navMoveNext;
            this.nav.MovePreviousItem = this.navMovePrev;
            this.nav.Name = "nav";
            this.nav.PositionItem = this.navPosition;
            this.nav.Size = new System.Drawing.Size(1100, 25);
            this.navMoveFirst.Name = "navMoveFirst";
            this.navMoveFirst.Text = "|<";
            this.navMoveFirst.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navMovePrev.Name = "navMovePrev";
            this.navMovePrev.Text = "<";
            this.navMovePrev.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navPosition.Name = "navPosition";
            this.navPosition.Size = new System.Drawing.Size(40, 25);
            this.navPosition.Text = "1";
            this.navCount.Name = "navCount";
            this.navCount.Text = "/ {0}";
            this.navMoveNext.Name = "navMoveNext";
            this.navMoveNext.Text = ">";
            this.navMoveNext.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navMoveLast.Name = "navMoveLast";
            this.navMoveLast.Text = ">|";
            this.navMoveLast.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;

            // pictureBox
            this.pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.pictureBox.Location = new System.Drawing.Point(40, 100);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(1020, 240);
            this.pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox.TabStop = false;

            this.lblRegNomer.AutoSize = false;
            this.lblRegNomer.BackColor = System.Drawing.Color.Transparent;
            this.lblRegNomer.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblRegNomer.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblRegNomer.Location = new System.Drawing.Point(60, 370);
            this.lblRegNomer.Name = "lblRegNomer";
            this.lblRegNomer.Size = new System.Drawing.Size(160, 28);
            this.lblRegNomer.Text = "Рег. номер:";
            this.lblRegNomer.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtRegNomer.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtRegNomer.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegNomer.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRegNomer.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtRegNomer.Location = new System.Drawing.Point(220, 370);
            this.txtRegNomer.Name = "txtRegNomer";
            this.txtRegNomer.Size = new System.Drawing.Size(300, 28);
            this.lblNomerKuzova.AutoSize = false;
            this.lblNomerKuzova.BackColor = System.Drawing.Color.Transparent;
            this.lblNomerKuzova.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblNomerKuzova.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblNomerKuzova.Location = new System.Drawing.Point(600, 370);
            this.lblNomerKuzova.Name = "lblNomerKuzova";
            this.lblNomerKuzova.Size = new System.Drawing.Size(160, 28);
            this.lblNomerKuzova.Text = "Номер кузова:";
            this.lblNomerKuzova.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtNomerKuzova.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtNomerKuzova.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNomerKuzova.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtNomerKuzova.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtNomerKuzova.Location = new System.Drawing.Point(760, 370);
            this.txtNomerKuzova.Name = "txtNomerKuzova";
            this.txtNomerKuzova.Size = new System.Drawing.Size(300, 28);
            this.lblNomerDvigatelya.AutoSize = false;
            this.lblNomerDvigatelya.BackColor = System.Drawing.Color.Transparent;
            this.lblNomerDvigatelya.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblNomerDvigatelya.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblNomerDvigatelya.Location = new System.Drawing.Point(60, 410);
            this.lblNomerDvigatelya.Name = "lblNomerDvigatelya";
            this.lblNomerDvigatelya.Size = new System.Drawing.Size(160, 28);
            this.lblNomerDvigatelya.Text = "Номер двигателя:";
            this.lblNomerDvigatelya.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtNomerDvigatelya.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtNomerDvigatelya.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNomerDvigatelya.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtNomerDvigatelya.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtNomerDvigatelya.Location = new System.Drawing.Point(220, 410);
            this.txtNomerDvigatelya.Name = "txtNomerDvigatelya";
            this.txtNomerDvigatelya.Size = new System.Drawing.Size(300, 28);
            this.lblGodVypuska.AutoSize = false;
            this.lblGodVypuska.BackColor = System.Drawing.Color.Transparent;
            this.lblGodVypuska.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblGodVypuska.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblGodVypuska.Location = new System.Drawing.Point(600, 410);
            this.lblGodVypuska.Name = "lblGodVypuska";
            this.lblGodVypuska.Size = new System.Drawing.Size(160, 28);
            this.lblGodVypuska.Text = "Год выпуска:";
            this.lblGodVypuska.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtGodVypuska.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtGodVypuska.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtGodVypuska.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtGodVypuska.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtGodVypuska.Location = new System.Drawing.Point(760, 410);
            this.txtGodVypuska.Name = "txtGodVypuska";
            this.txtGodVypuska.Size = new System.Drawing.Size(300, 28);
            this.lblProbeg.AutoSize = false;
            this.lblProbeg.BackColor = System.Drawing.Color.Transparent;
            this.lblProbeg.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblProbeg.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblProbeg.Location = new System.Drawing.Point(60, 450);
            this.lblProbeg.Name = "lblProbeg";
            this.lblProbeg.Size = new System.Drawing.Size(160, 28);
            this.lblProbeg.Text = "Пробег:";
            this.lblProbeg.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtProbeg.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtProbeg.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtProbeg.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtProbeg.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtProbeg.Location = new System.Drawing.Point(220, 450);
            this.txtProbeg.Name = "txtProbeg";
            this.txtProbeg.Size = new System.Drawing.Size(300, 28);
            this.lblCenaAvto.AutoSize = false;
            this.lblCenaAvto.BackColor = System.Drawing.Color.Transparent;
            this.lblCenaAvto.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblCenaAvto.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblCenaAvto.Location = new System.Drawing.Point(600, 450);
            this.lblCenaAvto.Name = "lblCenaAvto";
            this.lblCenaAvto.Size = new System.Drawing.Size(160, 28);
            this.lblCenaAvto.Text = "Цена авто:";
            this.lblCenaAvto.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtCenaAvto.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtCenaAvto.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCenaAvto.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtCenaAvto.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtCenaAvto.Location = new System.Drawing.Point(760, 450);
            this.txtCenaAvto.Name = "txtCenaAvto";
            this.txtCenaAvto.Size = new System.Drawing.Size(300, 28);
            this.lblCenaDnyaProkata.AutoSize = false;
            this.lblCenaDnyaProkata.BackColor = System.Drawing.Color.Transparent;
            this.lblCenaDnyaProkata.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblCenaDnyaProkata.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblCenaDnyaProkata.Location = new System.Drawing.Point(60, 490);
            this.lblCenaDnyaProkata.Name = "lblCenaDnyaProkata";
            this.lblCenaDnyaProkata.Size = new System.Drawing.Size(160, 28);
            this.lblCenaDnyaProkata.Text = "Цена/день:";
            this.lblCenaDnyaProkata.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtCenaDnyaProkata.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtCenaDnyaProkata.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCenaDnyaProkata.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtCenaDnyaProkata.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtCenaDnyaProkata.Location = new System.Drawing.Point(220, 490);
            this.txtCenaDnyaProkata.Name = "txtCenaDnyaProkata";
            this.txtCenaDnyaProkata.Size = new System.Drawing.Size(300, 28);
            this.lblDataTO.AutoSize = false;
            this.lblDataTO.BackColor = System.Drawing.Color.Transparent;
            this.lblDataTO.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblDataTO.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblDataTO.Location = new System.Drawing.Point(600, 490);
            this.lblDataTO.Name = "lblDataTO";
            this.lblDataTO.Size = new System.Drawing.Size(160, 28);
            this.lblDataTO.Text = "Дата ТО:";
            this.lblDataTO.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtDataTO.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtDataTO.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDataTO.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDataTO.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtDataTO.Location = new System.Drawing.Point(760, 490);
            this.txtDataTO.Name = "txtDataTO";
            this.txtDataTO.Size = new System.Drawing.Size(300, 28);
            this.lblOtmetki.AutoSize = false;
            this.lblOtmetki.BackColor = System.Drawing.Color.Transparent;
            this.lblOtmetki.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblOtmetki.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblOtmetki.Location = new System.Drawing.Point(60, 530);
            this.lblOtmetki.Name = "lblOtmetki";
            this.lblOtmetki.Size = new System.Drawing.Size(160, 28);
            this.lblOtmetki.Text = "Отметки:";
            this.lblOtmetki.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtOtmetki.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtOtmetki.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOtmetki.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtOtmetki.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtOtmetki.Location = new System.Drawing.Point(220, 530);
            this.txtOtmetki.Name = "txtOtmetki";
            this.txtOtmetki.Size = new System.Drawing.Size(300, 28);
            this.lblVozvrachen.AutoSize = false;
            this.lblVozvrachen.BackColor = System.Drawing.Color.Transparent;
            this.lblVozvrachen.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblVozvrachen.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblVozvrachen.Location = new System.Drawing.Point(600, 530);
            this.lblVozvrachen.Name = "lblVozvrachen";
            this.lblVozvrachen.Size = new System.Drawing.Size(160, 28);
            this.lblVozvrachen.Text = "Возвращён:";
            this.lblVozvrachen.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chkVozvrachen.AutoSize = false;
            this.chkVozvrachen.BackColor = System.Drawing.Color.Transparent;
            this.chkVozvrachen.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.chkVozvrachen.Location = new System.Drawing.Point(760, 534);
            this.chkVozvrachen.Name = "chkVozvrachen";
            this.chkVozvrachen.Size = new System.Drawing.Size(20, 20);
            this.lblKodMarki.AutoSize = false;
            this.lblKodMarki.BackColor = System.Drawing.Color.Transparent;
            this.lblKodMarki.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodMarki.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodMarki.Location = new System.Drawing.Point(60, 570);
            this.lblKodMarki.Name = "lblKodMarki";
            this.lblKodMarki.Size = new System.Drawing.Size(160, 28);
            this.lblKodMarki.Text = "Марка:";
            this.lblKodMarki.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodMarki.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodMarki.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodMarki.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodMarki.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodMarki.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodMarki.Location = new System.Drawing.Point(220, 570);
            this.cmbKodMarki.Name = "cmbKodMarki";
            this.cmbKodMarki.Size = new System.Drawing.Size(300, 25);
            this.lblKodMehanika.AutoSize = false;
            this.lblKodMehanika.BackColor = System.Drawing.Color.Transparent;
            this.lblKodMehanika.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodMehanika.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodMehanika.Location = new System.Drawing.Point(600, 570);
            this.lblKodMehanika.Name = "lblKodMehanika";
            this.lblKodMehanika.Size = new System.Drawing.Size(160, 28);
            this.lblKodMehanika.Text = "Механик:";
            this.lblKodMehanika.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodMehanika.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodMehanika.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodMehanika.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodMehanika.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodMehanika.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodMehanika.Location = new System.Drawing.Point(760, 570);
            this.cmbKodMehanika.Name = "cmbKodMehanika";
            this.cmbKodMehanika.Size = new System.Drawing.Size(300, 25);

            // btnFirst
            this.btnFirst.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnFirst.Text = "Первая";
            this.btnFirst.Location = new System.Drawing.Point(60, 640);
            this.btnFirst.Size = new System.Drawing.Size(130, 36);
            this.btnFirst.Name = "btnFirst";
            // btnPrev
            this.btnPrev.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnPrev.Text = "Предыдущая";
            this.btnPrev.Location = new System.Drawing.Point(200, 640);
            this.btnPrev.Size = new System.Drawing.Size(130, 36);
            this.btnPrev.Name = "btnPrev";
            // btnAdd
            this.btnAdd.Variant = CarRentalApp.Controls.BtnVariant.Add;
            this.btnAdd.Text = "Добавить";
            this.btnAdd.Location = new System.Drawing.Point(340, 640);
            this.btnAdd.Size = new System.Drawing.Size(130, 36);
            this.btnAdd.Name = "btnAdd";
            // btnSave
            this.btnSave.Variant = CarRentalApp.Controls.BtnVariant.Save;
            this.btnSave.Text = "Сохранить";
            this.btnSave.Location = new System.Drawing.Point(480, 640);
            this.btnSave.Size = new System.Drawing.Size(130, 36);
            this.btnSave.Name = "btnSave";
            // btnReport
            this.btnReport.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnReport.Text = "Отчёт";
            this.btnReport.Location = new System.Drawing.Point(620, 640);
            this.btnReport.Size = new System.Drawing.Size(180, 36);
            this.btnReport.Name = "btnReport";

            // btnLast
            this.btnLast.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnLast.Text = "Последняя";
            this.btnLast.Location = new System.Drawing.Point(60, 685);
            this.btnLast.Size = new System.Drawing.Size(130, 36);
            this.btnLast.Name = "btnLast";
            // btnNext
            this.btnNext.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnNext.Text = "Следующая";
            this.btnNext.Location = new System.Drawing.Point(200, 685);
            this.btnNext.Size = new System.Drawing.Size(130, 36);
            this.btnNext.Name = "btnNext";
            // btnDel
            this.btnDel.Variant = CarRentalApp.Controls.BtnVariant.Delete;
            this.btnDel.Text = "Удалить";
            this.btnDel.Location = new System.Drawing.Point(340, 685);
            this.btnDel.Size = new System.Drawing.Size(130, 36);
            this.btnDel.Name = "btnDel";
            // btnTable
            this.btnTable.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnTable.Text = "Табличная";
            this.btnTable.Location = new System.Drawing.Point(480, 685);
            this.btnTable.Size = new System.Drawing.Size(130, 36);
            this.btnTable.Name = "btnTable";
            // btnClose
            this.btnClose.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnClose.Text = "Закрыть";
            this.btnClose.Location = new System.Drawing.Point(620, 685);
            this.btnClose.Size = new System.Drawing.Size(180, 36);
            this.btnClose.Name = "btnClose";

            // Форма
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(18, 18, 20);
            this.ClientSize = new System.Drawing.Size(1100, 740);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.lblRegNomer);
            this.Controls.Add(this.txtRegNomer);
            this.Controls.Add(this.lblNomerKuzova);
            this.Controls.Add(this.txtNomerKuzova);
            this.Controls.Add(this.lblNomerDvigatelya);
            this.Controls.Add(this.txtNomerDvigatelya);
            this.Controls.Add(this.lblGodVypuska);
            this.Controls.Add(this.txtGodVypuska);
            this.Controls.Add(this.lblProbeg);
            this.Controls.Add(this.txtProbeg);
            this.Controls.Add(this.lblCenaAvto);
            this.Controls.Add(this.txtCenaAvto);
            this.Controls.Add(this.lblCenaDnyaProkata);
            this.Controls.Add(this.txtCenaDnyaProkata);
            this.Controls.Add(this.lblDataTO);
            this.Controls.Add(this.txtDataTO);
            this.Controls.Add(this.lblOtmetki);
            this.Controls.Add(this.txtOtmetki);
            this.Controls.Add(this.lblVozvrachen);
            this.Controls.Add(this.chkVozvrachen);
            this.Controls.Add(this.lblKodMarki);
            this.Controls.Add(this.cmbKodMarki);
            this.Controls.Add(this.lblKodMehanika);
            this.Controls.Add(this.cmbKodMehanika);
            this.Controls.Add(this.btnFirst);
            this.Controls.Add(this.btnPrev);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.btnReport);
            this.Controls.Add(this.btnLast);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnDel);
            this.Controls.Add(this.btnTable);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.nav);
            this.Controls.Add(this.header);
            this.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.Name = "AvtomobiliForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Автомобили";

            ((System.ComponentModel.ISupportInitialize)(this.bs)).EndInit();
            this.nav.ResumeLayout(false);
            this.nav.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nav)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
