namespace CarRentalApp.Forms
{
    partial class ProkatForm
    {
        private System.ComponentModel.IContainer components = null;
        private CarRentalApp.Controls.BandedHeader header;
        private System.Windows.Forms.BindingSource bs;
        private System.Windows.Forms.BindingNavigator nav;
        private System.Windows.Forms.ToolStripButton navMoveFirst;
        private System.Windows.Forms.ToolStripButton navMovePrev;
        private System.Windows.Forms.ToolStripTextBox navPosition;
        private System.Windows.Forms.ToolStripLabel navCount;
        private System.Windows.Forms.ToolStripButton navMoveNext;
        private System.Windows.Forms.ToolStripButton navMoveLast;
        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.Label lblDataVydachi;
        private System.Windows.Forms.TextBox txtDataVydachi;
        private System.Windows.Forms.Label lblSrok;
        private System.Windows.Forms.TextBox txtSrok;
        private System.Windows.Forms.Label lblDataVozvrata;
        private System.Windows.Forms.TextBox txtDataVozvrata;
        private System.Windows.Forms.Label lblCena;
        private System.Windows.Forms.TextBox txtCena;
        private System.Windows.Forms.Label lblOplachen;
        private System.Windows.Forms.CheckBox chkOplachen;
        private System.Windows.Forms.Label lblKodAvtomobilya;
        private System.Windows.Forms.ComboBox cmbKodAvtomobilya;
        private System.Windows.Forms.Label lblKodKlienta;
        private System.Windows.Forms.ComboBox cmbKodKlienta;
        private System.Windows.Forms.Label lblKodUslugi1;
        private System.Windows.Forms.ComboBox cmbKodUslugi1;
        private System.Windows.Forms.Label lblKodUslugi2;
        private System.Windows.Forms.ComboBox cmbKodUslugi2;
        private System.Windows.Forms.Label lblKodUslugi3;
        private System.Windows.Forms.ComboBox cmbKodUslugi3;
        private System.Windows.Forms.Label lblKodSotrudnika;
        private System.Windows.Forms.ComboBox cmbKodSotrudnika;
        private CarRentalApp.Controls.ColoredButton btnFirst;
        private CarRentalApp.Controls.ColoredButton btnPrev;
        private CarRentalApp.Controls.ColoredButton btnNext;
        private CarRentalApp.Controls.ColoredButton btnLast;
        private CarRentalApp.Controls.ColoredButton btnAdd;
        private CarRentalApp.Controls.ColoredButton btnDel;
        private CarRentalApp.Controls.ColoredButton btnSave;
        private CarRentalApp.Controls.ColoredButton btnTable;
        private CarRentalApp.Controls.ColoredButton btnReport;
        private CarRentalApp.Controls.ColoredButton btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.header = new CarRentalApp.Controls.BandedHeader();
            this.bs = new System.Windows.Forms.BindingSource(this.components);
            this.nav = new System.Windows.Forms.BindingNavigator(this.components);
            this.navMoveFirst = new System.Windows.Forms.ToolStripButton();
            this.navMovePrev = new System.Windows.Forms.ToolStripButton();
            this.navPosition = new System.Windows.Forms.ToolStripTextBox();
            this.navCount = new System.Windows.Forms.ToolStripLabel();
            this.navMoveNext = new System.Windows.Forms.ToolStripButton();
            this.navMoveLast = new System.Windows.Forms.ToolStripButton();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.lblDataVydachi = new System.Windows.Forms.Label();
            this.txtDataVydachi = new System.Windows.Forms.TextBox();
            this.lblSrok = new System.Windows.Forms.Label();
            this.txtSrok = new System.Windows.Forms.TextBox();
            this.lblDataVozvrata = new System.Windows.Forms.Label();
            this.txtDataVozvrata = new System.Windows.Forms.TextBox();
            this.lblCena = new System.Windows.Forms.Label();
            this.txtCena = new System.Windows.Forms.TextBox();
            this.lblOplachen = new System.Windows.Forms.Label();
            this.chkOplachen = new System.Windows.Forms.CheckBox();
            this.lblKodAvtomobilya = new System.Windows.Forms.Label();
            this.cmbKodAvtomobilya = new System.Windows.Forms.ComboBox();
            this.lblKodKlienta = new System.Windows.Forms.Label();
            this.cmbKodKlienta = new System.Windows.Forms.ComboBox();
            this.lblKodUslugi1 = new System.Windows.Forms.Label();
            this.cmbKodUslugi1 = new System.Windows.Forms.ComboBox();
            this.lblKodUslugi2 = new System.Windows.Forms.Label();
            this.cmbKodUslugi2 = new System.Windows.Forms.ComboBox();
            this.lblKodUslugi3 = new System.Windows.Forms.Label();
            this.cmbKodUslugi3 = new System.Windows.Forms.ComboBox();
            this.lblKodSotrudnika = new System.Windows.Forms.Label();
            this.cmbKodSotrudnika = new System.Windows.Forms.ComboBox();
            this.btnFirst = new CarRentalApp.Controls.ColoredButton();
            this.btnPrev = new CarRentalApp.Controls.ColoredButton();
            this.btnNext = new CarRentalApp.Controls.ColoredButton();
            this.btnLast = new CarRentalApp.Controls.ColoredButton();
            this.btnAdd = new CarRentalApp.Controls.ColoredButton();
            this.btnDel = new CarRentalApp.Controls.ColoredButton();
            this.btnSave = new CarRentalApp.Controls.ColoredButton();
            this.btnTable = new CarRentalApp.Controls.ColoredButton();
            this.btnReport = new CarRentalApp.Controls.ColoredButton();
            this.btnClose = new CarRentalApp.Controls.ColoredButton();
            ((System.ComponentModel.ISupportInitialize)(this.bs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nav)).BeginInit();
            this.nav.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();

            // header
            this.header.Title = "ПРОКАТ";
            this.header.Size = new System.Drawing.Size(1100, 56);

            // nav
            this.nav.AddNewItem = null;
            this.nav.BindingSource = this.bs;
            this.nav.CountItem = this.navCount;
            this.nav.DeleteItem = null;
            this.nav.Dock = System.Windows.Forms.DockStyle.Top;
            this.nav.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                this.navMoveFirst, this.navMovePrev, this.navPosition, this.navCount,
                this.navMoveNext, this.navMoveLast });
            this.nav.MoveFirstItem = this.navMoveFirst;
            this.nav.MoveLastItem = this.navMoveLast;
            this.nav.MoveNextItem = this.navMoveNext;
            this.nav.MovePreviousItem = this.navMovePrev;
            this.nav.Name = "nav";
            this.nav.PositionItem = this.navPosition;
            this.nav.Size = new System.Drawing.Size(1100, 25);
            this.navMoveFirst.Name = "navMoveFirst";
            this.navMoveFirst.Text = "|<";
            this.navMoveFirst.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navMovePrev.Name = "navMovePrev";
            this.navMovePrev.Text = "<";
            this.navMovePrev.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navPosition.Name = "navPosition";
            this.navPosition.Size = new System.Drawing.Size(40, 25);
            this.navPosition.Text = "1";
            this.navCount.Name = "navCount";
            this.navCount.Text = "/ {0}";
            this.navMoveNext.Name = "navMoveNext";
            this.navMoveNext.Text = ">";
            this.navMoveNext.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.navMoveLast.Name = "navMoveLast";
            this.navMoveLast.Text = ">|";
            this.navMoveLast.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;

            // pictureBox
            this.pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.pictureBox.Location = new System.Drawing.Point(40, 100);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(1020, 240);
            this.pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox.TabStop = false;

            this.lblDataVydachi.AutoSize = false;
            this.lblDataVydachi.BackColor = System.Drawing.Color.Transparent;
            this.lblDataVydachi.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblDataVydachi.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblDataVydachi.Location = new System.Drawing.Point(60, 370);
            this.lblDataVydachi.Name = "lblDataVydachi";
            this.lblDataVydachi.Size = new System.Drawing.Size(160, 28);
            this.lblDataVydachi.Text = "Дата выдачи:";
            this.lblDataVydachi.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtDataVydachi.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtDataVydachi.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDataVydachi.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDataVydachi.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtDataVydachi.Location = new System.Drawing.Point(220, 370);
            this.txtDataVydachi.Name = "txtDataVydachi";
            this.txtDataVydachi.Size = new System.Drawing.Size(300, 28);
            this.lblSrok.AutoSize = false;
            this.lblSrok.BackColor = System.Drawing.Color.Transparent;
            this.lblSrok.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblSrok.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblSrok.Location = new System.Drawing.Point(600, 370);
            this.lblSrok.Name = "lblSrok";
            this.lblSrok.Size = new System.Drawing.Size(160, 28);
            this.lblSrok.Text = "Срок (дн.):";
            this.lblSrok.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtSrok.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtSrok.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtSrok.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtSrok.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtSrok.Location = new System.Drawing.Point(760, 370);
            this.txtSrok.Name = "txtSrok";
            this.txtSrok.Size = new System.Drawing.Size(300, 28);
            this.lblDataVozvrata.AutoSize = false;
            this.lblDataVozvrata.BackColor = System.Drawing.Color.Transparent;
            this.lblDataVozvrata.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblDataVozvrata.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblDataVozvrata.Location = new System.Drawing.Point(60, 410);
            this.lblDataVozvrata.Name = "lblDataVozvrata";
            this.lblDataVozvrata.Size = new System.Drawing.Size(160, 28);
            this.lblDataVozvrata.Text = "Дата возврата:";
            this.lblDataVozvrata.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtDataVozvrata.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtDataVozvrata.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDataVozvrata.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDataVozvrata.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtDataVozvrata.Location = new System.Drawing.Point(220, 410);
            this.txtDataVozvrata.Name = "txtDataVozvrata";
            this.txtDataVozvrata.Size = new System.Drawing.Size(300, 28);
            this.lblCena.AutoSize = false;
            this.lblCena.BackColor = System.Drawing.Color.Transparent;
            this.lblCena.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblCena.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblCena.Location = new System.Drawing.Point(600, 410);
            this.lblCena.Name = "lblCena";
            this.lblCena.Size = new System.Drawing.Size(160, 28);
            this.lblCena.Text = "Цена:";
            this.lblCena.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.txtCena.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.txtCena.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCena.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtCena.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.txtCena.Location = new System.Drawing.Point(760, 410);
            this.txtCena.Name = "txtCena";
            this.txtCena.Size = new System.Drawing.Size(300, 28);
            this.lblOplachen.AutoSize = false;
            this.lblOplachen.BackColor = System.Drawing.Color.Transparent;
            this.lblOplachen.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblOplachen.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblOplachen.Location = new System.Drawing.Point(60, 450);
            this.lblOplachen.Name = "lblOplachen";
            this.lblOplachen.Size = new System.Drawing.Size(160, 28);
            this.lblOplachen.Text = "Оплачен:";
            this.lblOplachen.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chkOplachen.AutoSize = false;
            this.chkOplachen.BackColor = System.Drawing.Color.Transparent;
            this.chkOplachen.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.chkOplachen.Location = new System.Drawing.Point(220, 454);
            this.chkOplachen.Name = "chkOplachen";
            this.chkOplachen.Size = new System.Drawing.Size(20, 20);
            this.lblKodAvtomobilya.AutoSize = false;
            this.lblKodAvtomobilya.BackColor = System.Drawing.Color.Transparent;
            this.lblKodAvtomobilya.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodAvtomobilya.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodAvtomobilya.Location = new System.Drawing.Point(600, 450);
            this.lblKodAvtomobilya.Name = "lblKodAvtomobilya";
            this.lblKodAvtomobilya.Size = new System.Drawing.Size(160, 28);
            this.lblKodAvtomobilya.Text = "Авто:";
            this.lblKodAvtomobilya.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodAvtomobilya.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodAvtomobilya.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodAvtomobilya.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodAvtomobilya.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodAvtomobilya.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodAvtomobilya.Location = new System.Drawing.Point(760, 450);
            this.cmbKodAvtomobilya.Name = "cmbKodAvtomobilya";
            this.cmbKodAvtomobilya.Size = new System.Drawing.Size(300, 25);
            this.lblKodKlienta.AutoSize = false;
            this.lblKodKlienta.BackColor = System.Drawing.Color.Transparent;
            this.lblKodKlienta.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodKlienta.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodKlienta.Location = new System.Drawing.Point(60, 490);
            this.lblKodKlienta.Name = "lblKodKlienta";
            this.lblKodKlienta.Size = new System.Drawing.Size(160, 28);
            this.lblKodKlienta.Text = "Клиент:";
            this.lblKodKlienta.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodKlienta.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodKlienta.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodKlienta.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodKlienta.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodKlienta.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodKlienta.Location = new System.Drawing.Point(220, 490);
            this.cmbKodKlienta.Name = "cmbKodKlienta";
            this.cmbKodKlienta.Size = new System.Drawing.Size(300, 25);
            this.lblKodUslugi1.AutoSize = false;
            this.lblKodUslugi1.BackColor = System.Drawing.Color.Transparent;
            this.lblKodUslugi1.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodUslugi1.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodUslugi1.Location = new System.Drawing.Point(600, 490);
            this.lblKodUslugi1.Name = "lblKodUslugi1";
            this.lblKodUslugi1.Size = new System.Drawing.Size(160, 28);
            this.lblKodUslugi1.Text = "Услуга 1:";
            this.lblKodUslugi1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodUslugi1.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodUslugi1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodUslugi1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodUslugi1.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodUslugi1.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodUslugi1.Location = new System.Drawing.Point(760, 490);
            this.cmbKodUslugi1.Name = "cmbKodUslugi1";
            this.cmbKodUslugi1.Size = new System.Drawing.Size(300, 25);
            this.lblKodUslugi2.AutoSize = false;
            this.lblKodUslugi2.BackColor = System.Drawing.Color.Transparent;
            this.lblKodUslugi2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodUslugi2.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodUslugi2.Location = new System.Drawing.Point(60, 530);
            this.lblKodUslugi2.Name = "lblKodUslugi2";
            this.lblKodUslugi2.Size = new System.Drawing.Size(160, 28);
            this.lblKodUslugi2.Text = "Услуга 2:";
            this.lblKodUslugi2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodUslugi2.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodUslugi2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodUslugi2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodUslugi2.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodUslugi2.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodUslugi2.Location = new System.Drawing.Point(220, 530);
            this.cmbKodUslugi2.Name = "cmbKodUslugi2";
            this.cmbKodUslugi2.Size = new System.Drawing.Size(300, 25);
            this.lblKodUslugi3.AutoSize = false;
            this.lblKodUslugi3.BackColor = System.Drawing.Color.Transparent;
            this.lblKodUslugi3.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodUslugi3.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodUslugi3.Location = new System.Drawing.Point(600, 530);
            this.lblKodUslugi3.Name = "lblKodUslugi3";
            this.lblKodUslugi3.Size = new System.Drawing.Size(160, 28);
            this.lblKodUslugi3.Text = "Услуга 3:";
            this.lblKodUslugi3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodUslugi3.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodUslugi3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodUslugi3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodUslugi3.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodUslugi3.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodUslugi3.Location = new System.Drawing.Point(760, 530);
            this.cmbKodUslugi3.Name = "cmbKodUslugi3";
            this.cmbKodUslugi3.Size = new System.Drawing.Size(300, 25);
            this.lblKodSotrudnika.AutoSize = false;
            this.lblKodSotrudnika.BackColor = System.Drawing.Color.Transparent;
            this.lblKodSotrudnika.Font = new System.Drawing.Font("Segoe UI Semibold", 10.5F, System.Drawing.FontStyle.Bold);
            this.lblKodSotrudnika.ForeColor = System.Drawing.Color.FromArgb(229, 57, 53);
            this.lblKodSotrudnika.Location = new System.Drawing.Point(60, 570);
            this.lblKodSotrudnika.Name = "lblKodSotrudnika";
            this.lblKodSotrudnika.Size = new System.Drawing.Size(160, 28);
            this.lblKodSotrudnika.Text = "Сотрудник:";
            this.lblKodSotrudnika.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cmbKodSotrudnika.BackColor = System.Drawing.Color.FromArgb(30, 30, 34);
            this.cmbKodSotrudnika.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbKodSotrudnika.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbKodSotrudnika.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.cmbKodSotrudnika.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.cmbKodSotrudnika.Location = new System.Drawing.Point(220, 570);
            this.cmbKodSotrudnika.Name = "cmbKodSotrudnika";
            this.cmbKodSotrudnika.Size = new System.Drawing.Size(300, 25);

            // btnFirst
            this.btnFirst.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnFirst.Text = "Первая";
            this.btnFirst.Location = new System.Drawing.Point(60, 640);
            this.btnFirst.Size = new System.Drawing.Size(130, 36);
            this.btnFirst.Name = "btnFirst";
            // btnPrev
            this.btnPrev.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnPrev.Text = "Предыдущая";
            this.btnPrev.Location = new System.Drawing.Point(200, 640);
            this.btnPrev.Size = new System.Drawing.Size(130, 36);
            this.btnPrev.Name = "btnPrev";
            // btnAdd
            this.btnAdd.Variant = CarRentalApp.Controls.BtnVariant.Add;
            this.btnAdd.Text = "Добавить";
            this.btnAdd.Location = new System.Drawing.Point(340, 640);
            this.btnAdd.Size = new System.Drawing.Size(130, 36);
            this.btnAdd.Name = "btnAdd";
            // btnSave
            this.btnSave.Variant = CarRentalApp.Controls.BtnVariant.Save;
            this.btnSave.Text = "Сохранить";
            this.btnSave.Location = new System.Drawing.Point(480, 640);
            this.btnSave.Size = new System.Drawing.Size(130, 36);
            this.btnSave.Name = "btnSave";
            // btnReport
            this.btnReport.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnReport.Text = "Отчёт";
            this.btnReport.Location = new System.Drawing.Point(620, 640);
            this.btnReport.Size = new System.Drawing.Size(180, 36);
            this.btnReport.Name = "btnReport";

            // btnLast
            this.btnLast.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnLast.Text = "Последняя";
            this.btnLast.Location = new System.Drawing.Point(60, 685);
            this.btnLast.Size = new System.Drawing.Size(130, 36);
            this.btnLast.Name = "btnLast";
            // btnNext
            this.btnNext.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnNext.Text = "Следующая";
            this.btnNext.Location = new System.Drawing.Point(200, 685);
            this.btnNext.Size = new System.Drawing.Size(130, 36);
            this.btnNext.Name = "btnNext";
            // btnDel
            this.btnDel.Variant = CarRentalApp.Controls.BtnVariant.Delete;
            this.btnDel.Text = "Удалить";
            this.btnDel.Location = new System.Drawing.Point(340, 685);
            this.btnDel.Size = new System.Drawing.Size(130, 36);
            this.btnDel.Name = "btnDel";
            // btnTable
            this.btnTable.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnTable.Text = "Табличная";
            this.btnTable.Location = new System.Drawing.Point(480, 685);
            this.btnTable.Size = new System.Drawing.Size(130, 36);
            this.btnTable.Name = "btnTable";
            // btnClose
            this.btnClose.Variant = CarRentalApp.Controls.BtnVariant.Default;
            this.btnClose.Text = "Закрыть";
            this.btnClose.Location = new System.Drawing.Point(620, 685);
            this.btnClose.Size = new System.Drawing.Size(180, 36);
            this.btnClose.Name = "btnClose";

            // Форма
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(18, 18, 20);
            this.ClientSize = new System.Drawing.Size(1100, 740);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.lblDataVydachi);
            this.Controls.Add(this.txtDataVydachi);
            this.Controls.Add(this.lblSrok);
            this.Controls.Add(this.txtSrok);
            this.Controls.Add(this.lblDataVozvrata);
            this.Controls.Add(this.txtDataVozvrata);
            this.Controls.Add(this.lblCena);
            this.Controls.Add(this.txtCena);
            this.Controls.Add(this.lblOplachen);
            this.Controls.Add(this.chkOplachen);
            this.Controls.Add(this.lblKodAvtomobilya);
            this.Controls.Add(this.cmbKodAvtomobilya);
            this.Controls.Add(this.lblKodKlienta);
            this.Controls.Add(this.cmbKodKlienta);
            this.Controls.Add(this.lblKodUslugi1);
            this.Controls.Add(this.cmbKodUslugi1);
            this.Controls.Add(this.lblKodUslugi2);
            this.Controls.Add(this.cmbKodUslugi2);
            this.Controls.Add(this.lblKodUslugi3);
            this.Controls.Add(this.cmbKodUslugi3);
            this.Controls.Add(this.lblKodSotrudnika);
            this.Controls.Add(this.cmbKodSotrudnika);
            this.Controls.Add(this.btnFirst);
            this.Controls.Add(this.btnPrev);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.btnReport);
            this.Controls.Add(this.btnLast);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnDel);
            this.Controls.Add(this.btnTable);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.nav);
            this.Controls.Add(this.header);
            this.ForeColor = System.Drawing.Color.FromArgb(240, 240, 244);
            this.Name = "ProkatForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Прокат";

            ((System.ComponentModel.ISupportInitialize)(this.bs)).EndInit();
            this.nav.ResumeLayout(false);
            this.nav.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nav)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
